export { default as Banner } from './Banner'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
export { default as Offers } from './Offers'
export { default as About } from './About'
